# $Id$
common: &default_settings
  access_key_id: AKIAILGXT362XEREOEDQ
  secret_access_key: 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
  use_ssl: false
  
development:
  <<: *default_settings
  bucket_name: eternos_development
  use_ssl: false
  
test:
  <<: *default_settings
  bucket_name: eternos_test
  use_ssl: false
  
staging:
  <<: *default_settings
  bucket_name: eternos_staging
  
production:
  <<: *default_settings
  bucket_name: eternos
  