# $Id$
common: &default_settings
  invitation_required: true
  email_registration_required: false
  support_email: support@eternos.com
  # Set this to true if you want to require CC info when creating a trial account for a paid plan
  require_payment_info_for_trials: true
  # Credit card gateway: One of brain_tree, authorize_net_cim, payment_express, or trust_commerce
  gateway: brain_tree
  
development:
  <<: *default_settings
  app_name: Eternos Dev
  from_email: dev@eternos.com
  base_domain: dev.eternos.com
  FlashRecordingPath: /Applications/Red5/webapps/messageRecorder/streams
  s3_staging_dir: /tmp
  
test:
  <<: *default_settings
  invitation_required: false
  FlashRecordingPath: /Users/marcmauger/Documents/costasoft/projects/eternos.com/spec/fixtures
  app_name: Eternos Test
  from_email: test@eternos.com
  base_domain: localhost
  s3_staging_dir: /tmp
  
production:
  <<: *default_settings
  app_name: Eternos.com
  from_email: support@eternos.com
  base_domain: beta.eternos.com
  FlashRecordingPath: /opt/red5/webapps/messageRecorder/streams
  s3_staging_dir: /usr/local/eternos/cloud_staging
    
staging:
  <<: *default_settings
  invitation_required: true
  app_name: Eternos.com
  from_email: support@eternos.com
  base_domain: staging.eternos.com
  FlashRecordingPath: /opt/red5/webapps/messageRecorder/streams
  s3_staging_dir: /usr/local/eternos/cloud_staging
