# $Id$
common: &default_settings
  invitation_required: false
  email_registration_required: false
  support_email: support@eternos.com
  # Set this to true if you want to require CC info when creating a trial account for a paid plan
  require_payment_info_for_trials: true
  # Credit card gateway: One of brain_tree, authorize_net_cim, payment_express, or trust_commerce
  gateway: brain_tree
  
development:
  <<: *default_settings
  app_name: Eternos Dev
  from_email: dev@eternos.com
  base_domain: eternos
  FlashRecordingPath: /Applications/Red5/webapps/messageRecorder/streams
  
test:
  <<: *default_settings
  FlashRecordingPath: /Users/marcmauger/Documents/costasoft/projects/eternos.com/spec/fixtures
  app_name: Eternos Test
  from_email: test@eternos.com
  base_domain: localhost

production:
  <<: *default_settings
  app_name: Eternos
  from_email: support@eternos.com
  base_domain: eternos.com
  FlashRecordingPath: /opt/red5/webapps/messageRecorder/streams
    
staging:
  <<: *default_settings
  invitation_required: false
  app_name: Eternos Staging
  from_email: staging@eternos.com
  base_domain: staging.eternos.com
  FlashRecordingPath: /opt/red5/webapps/messageRecorder/streams