--- 
javascripts: 
- base: 
  - wysiwyg
  - unittest
  - timezone_detector
  - timer
  - timeline_helper
  - tabs
  - Swiff.Uploader
  - swfobject
  - soundmanager2
  - soundmanager2-nodebug-jsmin
  - sound
  - slideshow
  - slider
  - scroller
  - scrollable
  - scriptaculous
  - prototype
  - prototip
  - page-player
  - mootools-1.2-core-yc
  - mootools-1.2-core-nc
  - lowpro
  - login
  - lightbox
  - inplace_editor
  - inlineplayer
  - ga
  - Fx.ProgressBar
  - flowplayer-3.0.0-rc5.min
  - fckdragdrop
  - fckcustom
  - FancyUpload2
  - facebook
  - ejs
  - effects
  - draggable
  - dragdrop
  - defaultvalueactsashint
  - datepicker
  - date_selector
  - date
  - cvi_busy_lib
  - CustomFormElements
  - cookiejar
  - controls
  - builder
  - behaviors
  - backtothehtml
  - application_jquery
  - application
  - account_setup
  - accordion
stylesheets: 
- base: 
  - accordion
  - application
  - block
  - content_upload
  - datepicker
  - errors
  - forms
  - inlineplayer
  - jquery.autocomplete
  - member
  - page-player
  - popup
  - prelaunch
  - prototip
  - public
  - reset-fonts-grids
  - scaffold
  - screen
  - scrollable-navig
  - scrollable
  - soundmanager2
  - standard
  - style
  - tabs
  - timeline
