# $Id$
common: &default_settings
  tls: true
  server: smtp.gmail.com
  port: 587
  domain: eternos.com
  authentication: plain
  username: eternos-mailer@eternos.com
  password: UBy6XprJ50MhIE
  
development:
  <<: *default_settings

staging:
  <<: *default_settings
    
production:
  <<: *default_settings
