# $Id$
# Copy this file to config/key.yml and use a randomized key and salt

development:
  key: key
  salt: salt
  
test:
  key: key
  salt: salt
  
staging:
  key: supercrazyhellfury
  salt: 111222333
  
production:
  key: cr4zysh0oOmbLUsTT23rfcccrkkker
  salt: asshair000forme23
