# $Id$
# By default, NotRemoteRunner is used when RAILS_ENV == 'test'.
#
# You can pass options to memcached client by nesting the key value pairs
# under 'memcache_options'.
#
# You can also use a cluster of Starlings. Simply give a comma separated
# list of server:port, server:port, server:port values to listens_on. 
#
common: &default_settings
  listens_on: localhost:5672
    
development:
  <<: *default_settings
  
test:
  <<: *default_settings

cucumber:
  <<: *default_settings
  
staging:
  <<: *default_settings
  
local_production:
  <<: *default_settings

