#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

QusionAllowed = true
#RAILS_ROOT = File.join(File.dirname(__FILE__), '..') unless defined? RAILS_ROOT
#puts "Rails root = #{RAILS_ROOT}"

workling = File.join(File.dirname(__FILE__), '..', 'vendor', 'plugins', 'workling', 'script', 'listen.rb')
options = {
  :app_name   => "workling",
  :ARGV       => ARGV,
  :dir_mode   => :normal,
  :dir        => File.join(File.dirname(__FILE__), '..', 'log'),
  :log_output => true,
  :multiple   => false,
  :backtrace  => true,
  :monitor    => false
}

Daemons.run(workling, options)
