#!/usr/bin/env ruby
# 
# $Id$
# Munin plugin
# Counts running backup jobs

REQUEST_URI = 'http://beta.eternos.com/admin/munin/backup_job_avg_run_times?api=FL1mFl4mAlamB'
DATA_LABELS = %w( facebook twitter gmail blog picasa )

def output_config
  puts <<-END
graph_category Eternos.com
graph_title avg backups run times
graph_vlabel seconds

facebook.label Facebook
twitter.label Twitter
gmail.label Gmail
blog.label RSS
picasa.label Picasa
END
  exit 0
end

def output_values
  status = `curl -s #{REQUEST_URI}`
  
  unless $?.success?
    $stderr.puts "failed executing live_backups"
    exit 1
  end
  DATA_LABELS.each do |site|
    status =~ /#{site}\s+=\s+(\d+)/
    puts "#{site}.value #{$1}"
  end

end

if ARGV[0] == "config"
  output_config
else
  output_values
end