#!/usr/bin/env ruby
# 
# $Id$
# Munin plugin
# Counts running backup jobs

REQUEST_URI = 'http://eternos.local/admin/munin/backup_job_errors?api=FL1mFl4mAlamB'

def output_config
  schema_url = REQUEST_URI + '\&schema=1'
  schema = `curl -s #{schema_url}`
  
  unless $?.success?
    $stderr.puts "failed executing backup_errors"
    exit 1
  end
  
  puts <<-END
graph_category Eternos.com
graph_title backup errors
graph_vlabel count
END

  schema.scan(/^l_[a-f0-9]+\.label.*?$/) do |label|
    puts label
  end
  exit 0
end

def output_values
  status = `curl -s #{REQUEST_URI}`
  
  unless $?.success?
    $stderr.puts "failed executing backup_errors"
    exit 1
  end
  
  status.scan(/^l_[a-f0-9]+\.value.*?$/) do |value|
    puts value  
  end
end

if ARGV[0] == "config"
  output_config
else
  output_values
end