#!/usr/bin/env ruby
# 
# $Id$
# Munin plugin
# Counts total backup items by type

REQUEST_URI = 'http://beta.eternos.com/admin/munin/backup_items?api=FL1mFl4mAlamB'
DATA_LABELS = %w( facebook twitter emails rss_feeds rss_items facebook_photos picasa_photos )

def output_config
  puts <<-END
graph_category Eternos.com
graph_title backup data counts by type
graph_vlabel count

facebook.label Facebook Activity
twitter.label Twitter Tweets
emails.label Emails
rss_feeds.label RSS Items
rss_items.label RSS Feeds
facebook_photos.label Facebook Photos
picasa_photos.label Picasa Photos
END
  exit 0
end

def output_values
  status = `curl -s #{REQUEST_URI}`
  
  unless $?.success?
    $stderr.puts "failed executing live_backups"
    exit 1
  end
  DATA_LABELS.each do |site|
    status =~ /#{site}\s+=\s+(\d+)/
    puts "#{site}.value #{$1}"
  end

end

if ARGV[0] == "config"
  output_config
else
  output_values
end