#!/usr/bin/env ruby
# 
# $Id$
# Munin plugin
# Counts users (active & total)

REQUEST_URI = 'http://beta.eternos.com/admin/munin/users?api=FL1mFl4mAlamB'
DATA_LABELS = %w( sessions total active closed )

def output_config
  puts <<-END
graph_category Eternos.com
graph_title user stats
graph_vlabel count

sessions.label active sessions
total.label total users
active.label active users
closed.label closed accounts
END
  exit 0
end

def output_values
  status = `curl -s #{REQUEST_URI}`
  
  unless $?.success?
    $stderr.puts "failed executing eternos-users"
    exit 1
  end
  DATA_LABELS.each do |site|
    status =~ /#{site}\s+=\s+(\d+)/
    puts "#{site}.value #{$1}"
  end
end

if ARGV[0] == "config"
  output_config
else
  output_values
end