#!/usr/local/bin/python
# From https://github.com/hudora/hd-munin-plugins/

"""Returns the number of milliseconds it took to access an url."""

import urllib2
import sys
import os
import os.path
import signal
import time

def main():
    """Contains all useful work."""

    hostname = '.'.join(os.path.basename(sys.argv[0]).split('_')[1:])
    name = hostname.replace('.', '_')
    if 'url' in os.environ:
        url = os.environ['url']
    else:
       url = "http://%s/" % hostname
    
    if sys.argv[-1] == "config":
        print "graph_title http loadtime: %s" % url
        print 'graph_vlabel ms'
        print 'graph_args --lower-limit 0'
        print 'graph_category network'
        print '%s.label %s' % (name, url)
        print "%s.critical 9999" % (name,)

    else:
        # ensure there is a timeout after 10 seconds
        def handler(signum, frame):
            raise IOError, "Timeout"
        signal.signal(signal.SIGALRM, handler)
        signal.alarm(10)
        
        start = time.time()
        try:
            urllib2.urlopen(url).read()
        except:
            delta = 10
        else:
            delta = time.time() - start
        signal.alarm(0)
        delta = int(delta*1000)
        print "%s.value %s" % (name, delta)

main()
