#!/bin/sh
#
# Plugin to monitor the number of workling processes on the machine.
#
# Parameters:
#
#       config   (required)
#       autoconf (optional - used by munin-config)
#
#
# Magick markers (optional - used by munin-config and som installation
# scripts):
#%# family=auto
#%# capabilities=autoconf



if [ "$1" = "autoconf" ]; then
        echo yes 
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title Number of Workling Processes'
        echo 'graph_args --base 100 -l 0 '
        echo 'graph_vlabel number of processes'
        echo 'graph_category Eternos.com'
        echo 'graph_info This graph shows the number of Workling processes in the system.'
        echo 'processes.label Workling processes'
        echo 'processes.draw LINE2'
        echo 'processes.info The current number of Workling processes.'
        exit 0
fi

echo -n "processes.value "
ps eax | grep workling | grep -v grep | grep -v count | wc -l